#!/usr/bin/env bash
# This script extracts username, UID and home directory from /etc/passwd using while loop

while IFS=":" read -r username password uid gid gecos home shell
do
    echo "Username: $username, UID: $uid, Home: $home"
done < /etc/passwd
