#!/usr/bin/env bash
# Alternative version with while and IFS (cut olmadan)

while IFS=":" read -r username password uid gid gecos home shell
do
    echo "Username: $username, UID: $uid, Home: $home"
done < /etc/passwd
