#!/usr/bin/env bash
# This script displays username, user ID, and home directory from /etc/passwd

while IFS=":" read -r username _ userid _ _ home _
do
    echo "Username: $username, UID: $userid, Home: $home"
done < /etc/passwd
