#!/usr/bin/env bash
# Script to display username, UID and home directory from /etc/passwd

while IFS=: read -r username password uid gid gecos home shell; do
    echo "Username: $username, UID: $uid, Home: $home"
done < /etc/passwd
