#!/usr/bin/env bash
# This script does something

PID=$(ps -eo pid,cmd | grep "4-to_infinity_and_beyond" | grep -v "grep" | awk '{print $1}')

if [ -n "$PID" ]; then
    echo "Stopping 4-to_infinity_and_beyond process (PID: $PID)"
    echo "0" > "/proc/$PID/oom_score_adj" 2>/dev/null
    exec 3>"/proc/$PID/fd/0"
else
    echo "Process not found."
