#!/usr/bin/env bash 
# This script does something

# Find the PID of the 7-highlander process
PID=$(ps -eo pid,cmd | grep "[7]-highlander" | awk '{print $1}')

if [ -n "$PID" ]; then
    echo "Killing 7-highlander process with PID: $PID"
    kill "$PID"
else
    echo "7-highlander process not found."
fi
